// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwU61QbTynVP4-lNppJf6bGV_hfeXJJto',
    appId: '1:940475491046:web:9bef941a628ca7a6aa1127',
    messagingSenderId: '940475491046',
    projectId: 'flutter-notes-4687b',
    authDomain: 'flutter-notes-4687b.firebaseapp.com',
    storageBucket: 'flutter-notes-4687b.appspot.com',
    measurementId: 'G-C1293JX9T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE868BMn9f5z8RuGJ0eurc6DyhUMz0U2c',
    appId: '1:940475491046:android:293b9a91070966efaa1127',
    messagingSenderId: '940475491046',
    projectId: 'flutter-notes-4687b',
    storageBucket: 'flutter-notes-4687b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQtKoOq6YSZfOn6EOLlltrniFmzjdw-sc',
    appId: '1:940475491046:ios:b0b73524d5911a64aa1127',
    messagingSenderId: '940475491046',
    projectId: 'flutter-notes-4687b',
    storageBucket: 'flutter-notes-4687b.appspot.com',
    iosClientId: '940475491046-oaeob0lcibuitebol1hq7u1iq4vf3eua.apps.googleusercontent.com',
    iosBundleId: 'com.infinity.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQtKoOq6YSZfOn6EOLlltrniFmzjdw-sc',
    appId: '1:940475491046:ios:b0b73524d5911a64aa1127',
    messagingSenderId: '940475491046',
    projectId: 'flutter-notes-4687b',
    storageBucket: 'flutter-notes-4687b.appspot.com',
    iosClientId: '940475491046-oaeob0lcibuitebol1hq7u1iq4vf3eua.apps.googleusercontent.com',
    iosBundleId: 'com.infinity.notesApp',
  );
}
